# Generated by Django 5.2.8 on 2026-05-09 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly label, e.g. "Kitchen Fridge" or "Bedroom AC".', max_length=100)),
                ('appliance_type', models.CharField(choices=[('AC', 'Air Conditioner'), ('FRIDGE', 'Fridge'), ('LIGHT', 'Light'), ('WASHING_MACHINE', 'Washing Machine'), ('WATER_HEATER', 'Water Heater'), ('TV', 'Television')], max_length=20)),
                ('power_rating_kw', models.FloatField(help_text='Manufacturer-rated power draw in kilowatts (e.g. 1.5 for a typical AC).')),
                ('is_on', models.BooleanField(default=False)),
                ('is_faulty', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
