# Generated by Django 5.2.8 on 2026-05-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('strategy_type', models.CharField(choices=[('FlatRate', 'Flat Rate'), ('TimeOfUse', 'Time of Use'), ('GreenEnergy', 'Green Energy')], max_length=20)),
                ('base_rate', models.FloatField(help_text='Cost per kWh in pence (e.g. 28.0 = 28p/kWh).')),
                ('peak_rate', models.FloatField(default=0.0, help_text='Peak-hour cost per kWh in pence (TimeOfUse only).')),
                ('peak_start_hour', models.IntegerField(default=7, help_text='Hour (0–23) when peak pricing starts, e.g. 7 = 7 am.')),
                ('peak_end_hour', models.IntegerField(default=22, help_text='Hour (0–23) when peak pricing ends, e.g. 22 = 10 pm.')),
                ('green_discount_percent', models.FloatField(default=0.0, help_text='Percentage discount applied on top of base rate (GreenEnergy only).')),
                ('is_active', models.BooleanField(default=True, help_text='Only active plans appear in the homeowner dropdown.')),
            ],
        ),
    ]
