# Generated by Django 6.0.5 on 2026-05-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='green_discount_percent',
            field=models.FloatField(default=0.0, help_text='Percentage discount off base rate.'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='peak_end_hour',
            field=models.IntegerField(default=22, help_text='Hour (0-23) when peak pricing ends.'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='peak_rate',
            field=models.FloatField(default=0.0, help_text='Peak-hour cost per kWh in pence.'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='peak_start_hour',
            field=models.IntegerField(default=7, help_text='Hour (0-23) when peak pricing starts.'),
        ),
    ]
