# Generated by Django 6.0.5 on 2026-05-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_homeownersettings_has_solar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeownersettings',
            name='daily_threshold_kwh',
            field=models.FloatField(default=10.0),
        ),
    ]
