# Generated by Django 6.0.5 on 2026-05-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyusage',
            name='kwh_consumed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energyusage',
            name='recorded_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='faultticket',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(max_length=50),
        ),
    ]
